---
title: "Algorithmic Analysis for L0TF"
output:
  html_document:
    highlight: tango
    mathjax: null
    number_sections: yes
    theme: paper
    toc: yes
    toc_depth: 2
editor_options: 
  chunk_output_type: console
---
<style>
  body {font-size: 14pt; }
</style>

```{r setup, include=FALSE}
options(width=120)
knitr::opts_chunk$set(echo = TRUE, message=FALSE, message=FALSE)
```

# Load Simulation Functions

```{r}
library(AMIAS)
# -----------------------------------
# Toy Example: Piecewise Constant/Linear Simulation 
# -----------------------------------
ToyEx <- function(n, sigma=0.1, q=0, seed=NA) {
  tau = 0.5
  if (!is.na(seed)) set.seed(seed)
  x = seq(1/n, 1,length.out = n)
  if (q==0){
    y0 = 0*x; y0[x>tau] = 1
  }
  if (q==1) {
    y0 = 2*(tau-x); y0[x>tau] = 2*(x[x>tau]-tau)
  }
  y = y0 + sigma*rnorm(n)
  return(list(y = y, x = x, y0 = y0, tau = tau))  
}

# -----------------------------------
# Simu Example: Piecewise Constant/Linear Simulation 
#     Equal-spaced knots or Random Knots
# -----------------------------------
SimuEx <- function(n, sigma=0.1, q=0, nknot=4, seed=NA, RandKnot=FALSE, AdaKnot=FALSE) {
  if (!is.na(seed)) set.seed(seed)
  x = seq(1/n, 1,length.out = n)
  A=round(seq(0, n, length.out=nknot+2))[seq(2,nknot+1)]
  if(RandKnot) A = sort(sample(seq(6, n-5, 5), nknot))
  if(AdaKnot) A = round(seq(1, sqrt(n), length.out=nknot+2)^2)[seq(2,nknot+1)]
  tau = x[A]
  tau1 = c(0, tau, 1)
  if (q==0){
    aa = 1-seq(1,nknot+1)%%2
    y0 = 0*x
    for (j in 1:(nknot+1)) y0[x>tau1[j] & x<=tau1[j+1]] = aa[j]
  }
  if (q==1) {
    aa = 2*(-1)^seq(1,nknot+1)
    phi = rep(1, n)
    for (j in 1:(nknot+1)) phi = cbind(phi,pmin(pmax(x-tau1[j], 0), tau1[j+1]-tau1[j]))
    y0 = phi%*%c(0.5+1/(nknot+1),aa)
  }
  y = y0 + sigma*rnorm(n)
  return(list(y = y, x = x, y0 = y0, tau = tau, SetA = A))  
}

```

# Figure 7: Scatterplot of runtime versus sample size


```{r}
# nlist <- seq(100, 3000, 50)
# runtime <- array(0, c(length( nlist),100, 2))
# 
# for(i in seq_along(nlist)){
#   n <- nlist[i]
#   for(seed in 1:100){
#     
#     # Piecewise constant case
#     # Toy Piecewise constant/linear: one knot only 
#     q=0; sigma=0.1; nknot=1
#     data = ToyEx(n=n, q=q, sigma=sigma, seed=seed)
#     start_time <- Sys.time()
#     amias(data$y, D_type="tf0", k=nknot)
#     end_time <- Sys.time()
#     runtime[i, seed, 1] <- end_time - start_time
#     
#     q=1; sigma=0.1;  nknot=1
#     data = ToyEx(n=n, q=q, sigma=sigma, seed=seed)
#     start_time <- Sys.time()
#     amias(data$y, D_type="tfq", q=q, k=nknot)
#     end_time <- Sys.time()
#     runtime[i, seed, 2] <- end_time - start_time
#     
#   }
# }
# save.image("runtime_amias.RData")

```


```{r}
########################
## Runtime in amias
load("runtime_amias.RData")

t1 <- as.numeric(t(runtime[,,1]))
data <- cbind(rep(nlist, each=100), t1)
data <- as.data.frame(data)
colnames(data) <- c("n", "time")
library(ggplot2)
p1 <- ggplot(data = data, aes( x= n, y= time)) + geom_jitter(height = 0.0001, width=0) + 
  geom_smooth(method=lm, se= FALSE, size=2, color = "deepskyblue") +
  ggtitle("Example 1: Piecewise Constant") +
  labs(x="n", y = "Time (in seconds)") + 
  theme(axis.text.x = element_text(size = 10,color="black"),
        axis.title.x = element_text(size = 10,color="black"),
        axis.text.y = element_text(size = 10,color="black"),
        axis.title.y = element_text(size = 10,color="black"),
        plot.title = element_text(size = 10, hjust = 0.5))


t1 <- as.numeric(t(runtime[,,2]))
t1[which.max(t1)] <- NA
data <- cbind(rep(nlist, each=100), t1)
data <- as.data.frame(data)
colnames(data) <- c("n", "time")
library(ggplot2)
p2 <- ggplot(data = data, aes( x= n, y= time)) + geom_jitter(height = 0.0001, width=0) + 
  geom_smooth(method=lm, se= FALSE, size=2, color = "deepskyblue") +
  ggtitle("Example 2: Piecewise Linear") + 
  labs(x="n", y = "Time (in seconds)") + 
  theme(axis.text.x = element_text(size = 10,color="black"),
        axis.title.x = element_text(size = 10,color="black"),
        axis.text.y = element_text(size = 10,color="black"),
        axis.title.y = element_text(size = 10,color="black"),
        plot.title = element_text(size = 10, hjust = 0.5))


library("gridExtra")
# png("figs/amias_time_n.png", pointsize=6, width=850, height=400, res=120)
grid.arrange(p1, p2, ncol=2)
# dev.off()

```
# Figure 8: gitterplot of MSE versus sample size in Example 1 and Example 2


```{r}
# nlist <- seq(100, 1000, 100)
# mse <- array(0, c(length(nlist),100, 4))
# 
# for(i in seq_along(nlist)){
#   n <- nlist[i]
#   print(n)
#   for(seed in 1:100){
#     # Piecewise constant case
#     sigma=0.1; q=0; nknot = 1
#     data = ToyEx(n=n, q=q, sigma=sigma, seed=seed)
#     
#     op <- par(mfrow=c(1,4))
#     resL0 <- amias(data$y, D_type="tf0", k=nknot)
#     mse[i,seed,1] <- mean((as.numeric(data$y)-resL0$alpha)^2)
#     plot(resL0)
#     
#     resL0 <- amias(data$y, D_type="tf0", k=nknot, A = sample(n-q-1, nknot))
#     mse[i,seed,2] <- mean((as.numeric(data$y)-resL0$alpha)^2)
#     plot(resL0)
#     par(op)
#     
#     sigma=0.1; q=1; nknot = 1
#     data = ToyEx(n=n, q=q, sigma=sigma, seed=seed)
#     
#     resL0 <- amias(data$y, D_type="tfq", q=q, k=nknot)
#     mse[i,seed,3] <- mean((as.numeric(data$y)-resL0$alpha)^2)
#     plot(resL0)
#     
#     resL0 <- amias(data$y, D_type="tfq", q=q,  k=nknot, A = sample(n-q-1, nknot))
#     mse[i,seed,4] <- mean((as.numeric(data$y)-resL0$alpha)^2)
#     plot(resL0)
#     
#     
#   }
# }
# save.image("amias_mse_n_single.RData")
```


```{r}
load("amias_mse_n_single.RData")
title <- c("Example 1: Empty Set Initialization", "Example 1: Ramdom Set Initialization", "Example 2: Empty Set Initialization", "Example 2: Ramdom Set Initialization")
p <- list()
for(j in 1:4){
  t1 <- as.numeric(t(mse[,,j]))
  data <- cbind(rep(nlist, each=100), t1)
  data <- as.data.frame(data)
  colnames(data) <- c("n", "time")
  library(ggplot2)
  p[[j]] <- ggplot(data = data, aes( x= n, y= time)) + geom_jitter()+ 
    ggtitle(title[j]) + 
    labs(x="n", y = "MSE") + 
    theme(axis.text.x = element_text(size = 10,color="black"),
          axis.title.x = element_text(size = 10,color="black"),
          axis.text.y = element_text(size = 10,color="black"),
          axis.title.y = element_text(size = 10,color="black"),
          plot.title = element_text(size = 10, hjust = 0.5))
}

grid.arrange(p[[1]], p[[2]], p[[3]], p[[4]], ncol=2)


title <- c("Example 1: Piecewise Constant","Example 1: Piecewise Constant",  "Example 2: Piecewise Linear", "Example 2: Piecewise Linear")
p <- list()
for(j in 1:4){
  t1 <- as.numeric(t(mse[,,j]))
  data <- cbind(rep(nlist, each=100), t1)
  data <- as.data.frame(data)
  colnames(data) <- c("n", "time")
  library(ggplot2)
  p[[j]] <- ggplot(data = data, aes( x= n, y= time)) + geom_jitter()+ 
    ggtitle(title[j]) + 
    labs(x="n", y = "MSE") + 
    theme(axis.text.x = element_text(size = 10,color="black"),
          axis.title.x = element_text(size = 10,color="black"),
          axis.text.y = element_text(size = 10,color="black"),
          axis.title.y = element_text(size = 10,color="black"),
          plot.title = element_text(size = 10, hjust = 0.5))
}

library("gridExtra")
# png("figs/amias_mse_n_1.png", pointsize=6, width=850, height=400, res=120)
grid.arrange(p[[1]], p[[3]], ncol=2)
# dev.off()
```


# Figure 9: Gitterplot of MSE versus sample size

```{r}

# nlist <- seq(100, 1000, 100)
# mse <- array(0, c(length(nlist),100, 4))
# 
# for(i in seq_along(nlist)){
#   n <- nlist[i]
#   print(n)
#   for(seed in 1:100){
#     # Piecewise constant case
#     sigma=0.1; q=0; nknot=2; 
#     data = SimuEx(n=n, sigma=sigma, q=q, nknot=nknot, seed=seed)
#     
#     op <- par(mfrow=c(1,4))
#     resL0 <- amias(data$y, D_type="tf0", k=nknot)
#     mse[i,seed,1] <- mean((as.numeric(data$y)-resL0$alpha)^2)
#     plot(resL0)
#     
#     resL0 <- amias(data$y, D_type="tf0", k=nknot, A = sample(n-q-1, nknot))
#     mse[i,seed,2] <- mean((as.numeric(data$y)-resL0$alpha)^2)
#     plot(resL0)
#     
#     resL0_1 <- amias(data$y, D_type="tf0", k=1)
#     resL0 <- amias(data$y, D_type="tf0", k=nknot, A = c(resL0_1$A, sample(setdiff(1:(n-q-1), resL0_1$A), 1)))
#     mse[i,seed,3] <- mean((as.numeric(data$y)-resL0$alpha)^2)
#     plot(resL0)
#     
#     resL0_1 <- amias(data$y, D_type="tf0", k=1)
#     resL0 <- amias(data$y, D_type="tf0", k=nknot, A = c(resL0_1$A, which.max(abs(resL0_1$u))))
#     mse[i,seed,4] <- mean((as.numeric(data$y)-resL0$alpha)^2)
#     plot(resL0)
#     par(op)
#     
#     
#   }
# }
# save.image("amias_mse_n.RData")
```


```{r}
load("amias_mse_n.RData")
title <- c("Empty Set Initialization", "Ramdom Set Initialization", "Stepwise Ramdom Set Initialization", "Warm Start Initialization")
p <- list()
for(j in 1:4){
  t1 <- as.numeric(t(mse[,,j]))
  data <- cbind(rep(nlist, each=100), t1)
  data <- as.data.frame(data)
  colnames(data) <- c("n", "time")
  library(ggplot2)
  p[[j]] <- ggplot(data = data, aes( x= n, y= time)) + geom_jitter()+ 
    ggtitle(title[j]) + 
    labs(x="n", y = "MSE") + 
    theme(axis.text.x = element_text(size = 10,color="black"),
          axis.title.x = element_text(size = 10,color="black"),
          axis.text.y = element_text(size = 10,color="black"),
          axis.title.y = element_text(size = 10,color="black"),
          plot.title = element_text(size = 10, hjust = 0.5))
}

library("gridExtra")
# png("figs/amias_mse_n.png", pointsize=6, width=850, height=800, res=120)
grid.arrange(p[[1]], p[[2]],p[[3]], p[[4]], ncol=2)
# dev.off()

```

# Figure 13: Scatterplot of number of the dtected knots against sample size

```{r}
# nlist <- seq(100, 2000, 100)
# re <- re_o <- re_u <- kest <- mse <- array(0, c(length(nlist),100, 2))
# 
# for(n in nlist){
#   print(n)
#   for(seed in 1:100){
#     
#     par(mfrow=c(1,2),mar=c(3,3,3,3))
#     # Piecewise constant case
#     sigma=0.1; q=0; nknot=8; 
#     data = SimuEx(n=n, sigma=sigma, q=q, nknot=nknot, seed=seed)
#     resL0 = samias(as.numeric(data$y), D_type="tf0", kmax=nknot+4)
#     # 
#     mse[n/100,seed,1] <- mean((as.numeric(data$y)-resL0$alpha)^2)
#     kest[n/100,seed,1] <- resL0$kopt
#     re[n/100,seed,1] <- nknot==resL0$kopt
#     re_o[n/100,seed,1] <- nknot<resL0$kopt
#     re_u[n/100,seed,1] <- nknot>resL0$kopt
#     
#     sigma=0.1; q=1; nknot=5; 
#     data = SimuEx(n=n, sigma=sigma, q=q, nknot=nknot, seed=seed)
#     resL0 = samias(as.numeric(data$y), D_type="tfq", q=q, kmax=nknot+4, adjust = TRUE )
#     mse[n/100,seed,2] <- mean((as.numeric(data$y)-resL0$alpha)^2)
#     
#     
#     kest[n/100,seed,2] <- resL0$kopt
#     
#     re[n/100,seed,2] <- nknot==resL0$kopt
#     re_o[n/100,seed,2] <- nknot<resL0$kopt
#     re_u[n/100,seed,2] <- nknot>resL0$kopt
#   }
# }
# 
# save.image("smias_k_n.RData")
```

```{r}
load("smias_k_n.RData")
library(ggplot2)
title <- c("Example 3: Piecewise Constant", "Example 4: Piecewise Linear")
p <- list()
for(j in 1:2){
t1 <- as.numeric(t(kest[,,j]))
data <- cbind(rep(nlist, each=100), t1)
data <- as.data.frame(data)
colnames(data) <- c("n", "k")

p[[j]] <- ggplot(data = data, aes( x= n, y= k)) + geom_point() +
      geom_smooth(method=lm, se= FALSE, size=2, color = "deepskyblue") + ggtitle(title[j]) +
      theme(axis.text.x = element_text(size = 10,color="black"),
            axis.title.x = element_text(size = 10,color="black"),
            axis.text.y = element_text(size = 10,color="black"),
            axis.title.y = element_text(size = 10,color="black"),
            plot.title = element_text(size = 10, hjust = 0.5))
}

p2 <- list()
for(j in 1:2){
  t1 <- as.numeric(t(mse[,,j]))
  data <- cbind(rep(nlist, each=100), t1)
  data <- as.data.frame(data)
  colnames(data) <- c("n", "mse")
  
  p2[[j]] <- ggplot(data = data, aes( x= n, y= mse)) + geom_point() +
       ggtitle(title[j]) +
      theme(axis.text.x = element_text(size = 10,color="black"),
            axis.title.x = element_text(size = 10,color="black"),
            axis.text.y = element_text(size = 10,color="black"),
            axis.title.y = element_text(size = 10,color="black"),
            plot.title = element_text(size = 10, hjust = 0.5))
}



library("gridExtra")

# png("figs/samias_k_n.png", pointsize=8, width=850, height=850, res=120)
grid.arrange(p[[1]], p[[2]], p2[[1]], p2[[2]], ncol=2)
# dev.off()

```

